name: github pages


on:
 schedule:
  - cron: "0 04 */4 * *"
 push:
   branches:
   - main

jobs:
  build-hugo:
    runs-on: [self-hosted]
    steps:
    - name: Init
      run: |
          echo "::add-mask::${{ secrets.PATH_HFFIN }}"
          echo "::add-mask::${{ secrets.PATH_HFEEF }}"
          echo "::add-mask::${{ secrets.PATH_HFFIE }}"
          echo "::add-mask::${{ secrets.PATH_FEDGE }}"
          echo "::add-mask::${{ secrets.MACHINE }}"
    - uses: actions/checkout@main
      with:
        repository: Project-Gutenberg/Pincong-data

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
  
    - name: Build Hogo
      run: hugo --minify --ignoreCache --templateMetrics --templateMetricsHints --config github.toml,base.toml -d ../public -s site -v

    - name: Deploy
      continue-on-error: true
      id: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_branch: gh-pages
        publish_dir: public
